import { Role } from "@/utils/casl/defineAbilityFor";
import { FieldTypeEnum, SectionEnum, TableField } from "@/utils/types/TableField.types";
import { AgeGroup } from "@/utils/types/utils.types";

export const defaultPersonFields: TableField[] = [
	// { key: "id", header: "ID", class: "pl-8 min-w-[6rem]", visible: false, section: SectionEnum.NONE },
	{
		key: "full_name",
		header: "Full Name",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: false,
	},
	{
		key: "first_name",
		header: "First Name",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
	},
	{
		key: "last_name",
		header: "Last Name",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
	},
	{
		key: "email",
		header: "Email Address",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
	},
	{
		key: "phone",
		header: "Mobile Number",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
	},
	{
		key: "gender",
		header: "Gender",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
		options: ["Male", "Female"],
	},
	{
		key: "marital_status",
		header: "Marital Status",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
		options: ["Single", "Married", "Divorced", "Widowed"],
	},
	{
		key: "date_of_visit",
		ori_key: "date_of_visit",
		header: "Date of Visit",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.DATE,
		section: SectionEnum.CHURCH_DETAILS,
		editable: true,
	},
	{
		key: "birth_date",
		ori_key: "birth_date",
		header: "Birth Date",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.DATE,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
	},

	{
		key: "occupation",
		header: "Occupation",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
	},

	{
		key: "regular_service",
		header: "Regular Service",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.CHURCH_DETAILS,
		editable: true,
		options: [
			"(Eng) 1st Service",
			"(Eng) 2nd Service",
			"(Eng) 3rd Service",
			"(BM) Service",
			"(Chinese) Service",
		],
	},
	{
		key: "age",
		header: "Age",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
	},
	{
		key: "age_group",
		header: "Age Group",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
		options: Object.values(AgeGroup),
	},
	{
		key: "address_line1",
		header: "Address Line 1",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
	},
	{
		key: "city",
		header: "Home City",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
	},
	{
		key: "state",
		header: "Home State",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
	},
	{
		key: "postcode",
		header: "Home Postcode",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.PERSONAL_INFORMATION,
		editable: true,
	},

	{
		key: "emergency_contact_name",
		header: "Emergency Contact Name",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.EMERGENCY_CONTACT,
		editable: true,
	},
	{
		key: "emergency_contact_phone",
		header: "Emergency Contact Phone",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.EMERGENCY_CONTACT,
		editable: true,
	},
	{
		key: "emergency_contact_relationship",
		header: "Emergency Contact Relationship",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.EMERGENCY_CONTACT,
		editable: true,
		options: [
			"Father",
			"Mother",
			"Guardian",
			"Spouse",
			"Sibling",
			"Friend",
		],
	},
	{
		key: "is_christian",
		header: "Are you a Christian?",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.CHURCH_DETAILS,
		editable: true,
		options: ["Yes", "No"],
	},
	{
		key: "f_cell_names",
		header: "Cell Groups",
		class: "min-w-[14rem]",
		visible: false,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.CHURCH_DETAILS,
		editable: false,
	},
	{
		key: "f_district_names",
		header: "Districts",
		class: "min-w-[14rem]",
		visible: false,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.CHURCH_DETAILS,
		editable: false,
	},
	{
		key: "roles",
		header: "Roles",
		class: "min-w-[14rem]",
		visible: false,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.CHURCH_DETAILS,
		editable: false,
		options: Object.values(Role),
	},
	{
		key: "year_accepted_christ",
		ori_key: "year_accepted_christ",
		header: "Year Accepted Christ",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.CHURCH_DETAILS,
		editable: true,
		options: Array.from(
			{ length: 100 },
			(_, i) => new Date().getFullYear() - i
		),
	},
	{
		key: "is_baptised",
		header: "Is Baptised",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.CHURCH_DETAILS,
		editable: true,
		options: ["Yes", "No"],
	},
	{
		key: "baptised_in_this_church",
		header: "Baptised in SIBKL",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.SELECT,
		section: SectionEnum.CHURCH_DETAILS,
		editable: true,
		options: ["Yes", "No"],
	},
	{
		key: "date_baptised",
		ori_key: "date_baptised",
		header: "Date of Baptism",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.DATE,
		section: SectionEnum.CHURCH_DETAILS,
		editable: true,
	},
	{
		key: "baptism_cert_number",
		header: "Baptism Cert No.",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.CHURCH_DETAILS,
		editable: true,
	},
	{
		key: "date_dna_session",
		ori_key: "date_dna_session",
		header: "DNA Date",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.DATE,
		section: SectionEnum.MEMBERSHIP_DETAILS,
		editable: true,
	},
	{
		key: "date_membership",
		ori_key: "date_membership",
		header: "Membership Date",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.DATE,
		section: SectionEnum.MEMBERSHIP_DETAILS,
		editable: true,
	},
	{
		key: "member_id",
		header: "Membership ID",
		class: "min-w-[12rem]",
		visible: true,
		type: FieldTypeEnum.TEXT,
		section: SectionEnum.MEMBERSHIP_DETAILS,
		editable: true,
	},
];

// Grouped by sections
export const groupedPersonFields = defaultPersonFields.reduce(
	(acc, field) => {
		if (!field.section || field.section == SectionEnum.NONE) return acc;
		const section = field.section;
		if (!acc[section]) acc[section] = [];
		acc[section].push(field);
		return acc;
	},
	{} as Record<string, TableField[]>
);

// export const inputComponentMap = {
//   text: SharedTextInput,
//   date: SharedDateInput,
//   select: SharedSelectInput,
//   multiselect: SharedSelectInput,
//   year: SharedDateInput
// };

// export const resolveInputComponent = (field: TableField) => inputComponentMap[field.type ?? "text"];
